<a href="https://colab.research.google.com/github/S-Panta/merojob_scraping/blob/main/Job_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [140]:
import csv
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [141]:
def extract(jobs,page):
  headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
  url=f'https://merojob.com/search/?q={jobs}&page={page}'
  response=requests.get(url,headers)
  soup=BeautifulSoup(response.text,'html.parser')
  return soup

In [148]:

def value(soup):
  tech_list=[]
  cards=soup.find_all('div',class_='card mt-3 hover-shadow')
  for items in cards:
    listed=[]
    Job=items.find('a').text.strip()
    Office=items.find('h3').text.strip()
    deadline=items.find('p').text.strip().strip('Apply Before:')
    location=items.find('div',class_='media-body').text.strip()
    tool=items.find_all('span',class_='badge badge-pill badge-light rounded text-muted')
    for technology in tool:
      tech_list.append(technology.text.strip())
    values={
        'Office':Office,
        'Position':Job,
        'Location':location,
        'Deadline':deadline,
        'Skills':tech_list,
    }
    job_list.append(values)
    tech_list=[]
  return

In [ ]:
jobs=input("Enter the position that you want to see the vacancy of:")
job_list=[]
range_index=int(input("Enter the number of pages:"))
if jobs.isalpha():
    # Your code to run the problem goes here
     for i in range(1,range_index,1):
      c=extract(jobs,i)
      value(c)

In [150]:
output=pd.DataFrame(job_list)
output

,Office,Position,Location,Deadline,Skills
0,Logpoint Nepal,Software Engineer (C),"Jawalakhel ,Lalitpur","2 weeks, 3 days from now","[Teamwork, Java, Python, Analytical Skills, C/..."
1,Tekvortex,Backend Developer (Python),"Jhamsikhel, Lalitpur","4 days, 6 hours from now","[Python, Dynamodb, Aws Lambda, Rds (Mysql), No..."
2,Logpoint Nepal,Senior Quality Assurance Engine…,"Jawalakhel ,Lalitpur","1 week, 5 days from now","[Communication, Java, Sql, Python Scripting, L..."
3,Merojob,Python Developer,"Kathmandu, Nepal","1 week, 1 day from now","[Python, Js, Vue, Django Framework, Nuxt, Tail..."
4,Codavatar,Senior Backend Developer (Pytho…,Kathmandu,6 hours from now,[]
5,Codavatar,Mid- Level Backend Developer (P…,"Kathmandu, Nepal","5 days, 6 hours from now","[Problem Solving, Multitasking, Time Managemen..."
6,Softech Ltd.,Backend Developer,Kathmandu,"3 days, 6 hours from now","[Communication, Problem Solving, Time Manageme..."
7,Inspiring Lab,Python Developer,"Khumaltaar, Lalitpur",6 hours from now,"[Python, Linux, Api, Software Engineering, Scr..."

In [145]:
output.to_excel('Excel_list.xlsx')